# Generated by Django 2.2.9 on 2020-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제목')),
                ('desc', models.TextField(verbose_name='내용')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
