# Generated by Django 2.2.9 on 2020-01-27 11:25

from django.db import migrations, models
import mysite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200127_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=mysite.utils.uuid_upload_to),
        ),
    ]
