# Generated by Django 2.2.9 on 2020-01-27 11:37

from django.db import migrations, models
import django.db.models.deletion
import mysite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200127_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('phone', models.CharField(max_length=200, verbose_name='전화번호')),
                ('address', models.CharField(max_length=800, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제목')),
                ('desc', models.TextField(verbose_name='내용')),
                ('price', models.PositiveIntegerField()),
                ('leftover', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to=mysite.utils.uuid_upload_to)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Maker', verbose_name='거래처')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='maker',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.Mate'),
        ),
    ]
