# Generated by Django 2.2.9 on 2020-01-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200127_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.Mate'),
        ),
    ]
