# Generated by Django 2.2.9 on 2020-01-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200127_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='item',
        ),
    ]
